x-db-environment: &db-environment
  POSTGRES_HOST: ${POSTGRES_HOST:-localhost}
  POSTGRES_PORT: ${POSTGRES_PORT:-5432}
  POSTGRES_DB: ${POSTGRES_DB:-database}
  POSTGRES_USER: ${POSTGRES_USER:-user}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
  POSTGRES_HOST_AUTH_METHOD: trust
  
  TZ: ${TZ:-UTC}

services:
  postgres:
    hostname: postgres
    container_name: postgres_container
    restart: unless-stopped
    image: postgres
    environment:
      PGDATA: /data/postgres      
      <<: *db-environment
    volumes:
      - ./postgres/data/:/data/postgres
    ports:
      - "5432:5432"

  server:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      <<: *db-environment
      POSTGRES_HOST: postgres
